### ISSUE TITLE
[BUG] Segmentation Fault - Special character in DB name

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [mydumper/mydumper#1469] opened 2024-04-12 17:40 UTC
The latest version of myloader is used.

gdb bt output:
```
#0  0x00007ffff7924447 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7924703 in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00005555555afe79 in m_critical (fmt=0x5555556cb4c0 "Thread %d: Error switching to database `%s` %s") at /tmp/src/mydumper/src/common.c:752
#3  0x00005555555b5144 in execute_use_if_needs_to (td=0x555555dbec60, database=0x7fffc8036410, msg=0x5555556ce2be "Restoring table structure") at /tmp/src/mydumper/src/myloader_common.c:227
#4  0x00005555555bc484 in process_schema (td=0x555555dbec60) at /tmp/src/mydumper/src/myloader_worker_schema.c:138
#5  0x00005555555bcb22 in worker_schema_thread (td=0x555555dbec60) at /tmp/src/mydumper/src/myloader_worker_schema.c:237
#6  0x00007ffff794aa51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7294ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff7326850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Context: 

When I ran this myloader it kept failing, then I tried to restore only one database. That time I got this error message.

```
** (myloader:22486): CRITICAL **: 17:39:44.265: Thread 51: Error switching to database `a&b` Restoring table structure
```

Is there any way to fix this? 

### Update 1

I tried to remove those schema & data files related to that and restore, again the error with the SQL file of an proper file.

```
Thread 12 "myloader" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffddffb640 (LWP 23447)]
cmp_restore_job (rj1=0x7fffc412a570, rj2=0x555555ecb620) at /tmp/src/mydumper/src/myloader_process.c:690
690     /tmp/src/mydumper/src/myloader_process.c: No such file or directory.
(gdb) bt
#0  cmp_restore_job (rj1=0x7fffc412a570, rj2=0x555555ecb620) at /tmp/src/mydumper/src/myloader_process.c:690
#1  0x00007ffff7916918 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00005555555b4413 in process_data_filename (filename=0x555555f25ff0 "demo.png_demo.00000.01873.sql") at /tmp/src/mydumper/src/myloader_process.c:722
#3  0x00005555555baf64 in process_filename (filename=0x555555f25ff0 "demo.png_demo.00000.01873.sql") at /tmp/src/mydumper/src/myloader_intermediate_queue.c:170
#4  0x00005555555bb0c2 in process_stream_filename (iflnm=0x555555f25fd0) at /tmp/src/mydumper/src/myloader_intermediate_queue.c:208
#5  0x00005555555bb24c in intermediate_thread () at /tmp/src/mydumper/src/myloader_intermediate_queue.c:246
#6  0x00007ffff794aa51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7294ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff7326850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
When I open the contents are proper. I don't see anything suspicious.

**Comment by davidducos** [comment] 2024-04-15 12:40
I think that it has been fixed in https://github.com/mydumper/mydumper/pull/1455
Can you compile master and test it again?

**Comment by davidducos** [comment] 2024-05-02 14:48
Hi @BhuviTheDataGuy ,
I was not able to reproduce your issue on v0.16.1-3 or master. 
I closing this and let us now if you still have the issue with latest prerelease, if so, please share a test case.

**Closed by davidducos** 2024-05-02 14:48 UTC
Labels: bug
