### ISSUE TITLE
Mydumper compile error at connection.c

### ISSUE THREAD

**Issue by bhavitha8883** [mydumper/mydumper#808] opened 2022-08-24 01:29 UTC
**To Reproduce**
Command executed:
Building  a custom docker image with 0.11.5

What mydumper and myloader version has been used?
0.11.5
**Expected behavior**
Image 0.11.5 should be built.

**Log**
#6 2.322 + make
#6 2.371 Scanning dependencies of target myloader
#6 2.388 [  5%] Building C object CMakeFiles/myloader.dir/myloader.c.o
#6 3.031 [ 11%] Building C object CMakeFiles/myloader.dir/server_detect.c.o
#6 3.128 [ 17%] Building C object CMakeFiles/myloader.dir/connection.c.o
#6 3.181 /mydumper-0.11.5/connection.c: In function 'configure_connection':
#6 3.181 /mydumper-0.11.5/connection.c:49:9: error: 'SSL_MODE_REQUIRED' undeclared (first use in this function)
#6 3.181      i = SSL_MODE_REQUIRED;
#6 3.181          ^~~~~~~~~~~~~~~~~
#6 3.181 /mydumper-0.11.5/connection.c:49:9: note: each undeclared identifier is reported only once for each function it appears in
#6 3.183 /mydumper-0.11.5/connection.c:50:25: error: 'MYSQL_OPT_SSL_MODE' undeclared (first use in this function); did you mean 'MYSQL_OPT_SSL_CRL'?
#6 3.183      mysql_options(conn, MYSQL_OPT_SSL_MODE, &i);
#6 3.183                          ^~~~~~~~~~~~~~~~~~
#6 3.183                          MYSQL_OPT_SSL_CRL
#6 3.186 /mydumper-0.11.5/connection.c:54:13: error: 'SSL_MODE_DISABLED' undeclared (first use in this function); did you mean 'SS_DISABLE'?
#6 3.186          i = SSL_MODE_DISABLED;
#6 3.186              ^~~~~~~~~~~~~~~~~
#6 3.186              SS_DISABLE
#6 3.190 /mydumper-0.11.5/connection.c:57:13: error: 'SSL_MODE_PREFERRED' undeclared (first use in this function)
#6 3.190          i = SSL_MODE_PREFERRED;
#6 3.190              ^~~~~~~~~~~~~~~~~~
#6 3.193 /mydumper-0.11.5/connection.c:63:13: error: 'SSL_MODE_VERIFY_CA' undeclared (first use in this function)
#6 3.193          i = SSL_MODE_VERIFY_CA;
#6 3.193              ^~~~~~~~~~~~~~~~~~
#6 3.198 /mydumper-0.11.5/connection.c:66:13: error: 'SSL_MODE_VERIFY_IDENTITY' undeclared (first use in this function)
#6 3.198          i = SSL_MODE_VERIFY_IDENTITY;
#6 3.198              ^~~~~~~~~~~~~~~~~~~~~~~~
#6 3.202 make[2]: *** [CMakeFiles/myloader.dir/build.make:89: CMakeFiles/myloader.dir/connection.c.o] Error 1
#6 3.202 make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/myloader.dir/all] Error 2
#6 3.202 make: *** [Makefile:130: all] Error 2

**Environment (please complete the following information):**
Dockerfile:
FROM debian:buster

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
  build-essential \
  cmake \
  libglib2.0-dev \
  lsb-release \
  gnupg \
  default-libmysqlclient-dev \ 
  zlib1g-dev \
  libpcre3-dev \
  libssl-dev bash python python-pip unzip groff gzip \

ENV RELEASE_VERSION=0.11.5 
RUN set -ex \
    && curl -L -o mydumper.tar.gz --silent https://github.com/maxbube/mydumper/archive/v${RELEASE_VERSION}.tar.gz \
    && tar -xzf mydumper.tar.gz && rm -f mydumper.tar.gz \
    && cd mydumper-${RELEASE_VERSION} \
    && cmake . \
    && make \
    && make install
 

-  - MyDumper version: 0.11.5
---

is there any library am i missing to compile it in my dockerfile please help me here??(FYI- i could able to build 0.9.5 without any issues)
Thank you so much in advance.

**Comment by davidducos** [comment] 2022-08-24 11:50
Hi @bhavitha8883
you are using MariaDB libraries, then you should be using: -DWITH_SSL=OFF
Please, review this link:
https://github.com/mydumper/mydumper#how-to-build-it
And also this one as you are compiling on docker:
https://github.com/mydumper/mydumper#build-docker-image

BTW, you should be compiling latest version if you want me to help you efficiently. I'm closing this as it is not a bug.

**Closed by davidducos** 2022-08-24 11:50 UTC
Labels: bug

**Comment by bhavitha8883** [comment] 2022-08-24 15:28
Thank you so much @davidducos for the very quick response, i could able to build now(Built latest as per your suggestion).

**Comment by drawks** [comment] 2022-11-11 19:47
It would be nice if the cmake setup detected which dev headers were in use and set the correct defines.
