### ISSUE TITLE
[BUG] Schema index checksum mismatch found!

### ISSUE THREAD

**Issue by fazi1058** [mydumper/mydumper#862] opened 2022-10-24 11:01 UTC
Hello!
I am using myloader and mydumper for taking bakup and restore them.But  when I restore backup  I encounter with errors below:

```** (myloader:2868268): WARNING **: 10:04:25.349: Schema index checksum mismatch found for `db_name`.`orders`. Got '83671d4e', expecting 'CB0C64DE' in file: db_name.orders-schema-indexes-checksum```

```** (myloader:2868268): WARNING **: 10:04:24.369: Schema index checksum mismatch found for `db_name`.`demo__orders`. Got '40fd4431', expecting '160AD7C6' in file: db_name.demo__orders-schema-indexes-checksum```

**My question is that : Should I be worried? because all checksum for data and their schema was OK except these two! How does it effect? How it is happening?**

mydmper command:

mydumper   --database=$DB_NAME   --user=$DB_USER   --outputdir=/Backup/$DB_NAME--$DATE   --build-empty-files   --trx-consistency-only --compress --checksum-all

myloader command:

myloader -t 32 -d db_name  --serialized-table-creation  --verbose 3 -B db_name

**Comment by davidducos** [comment] 2022-10-26 11:51
Hi @fazi1058, can you share the SHOW CREATE TABLE from the database you exported and the database you imported?

**Comment by fazi1058** [comment] 2022-11-01 09:05
I am afraid I can't share table structure with you but when I ran  query the only difference between them was auto_increment:
```
< ) ENGINE=InnoDB AUTO_INCREMENT=587030163 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
---
> ) ENGINE=InnoDB AUTO_INCREMENT=615939773 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
```
first one belongs to the  database I imported and second one belongs to database I got export from.

**Comment by davidducos** [comment] 2022-11-01 13:08
Hi @fazi1058 , this has been already reported by @stephanie-dba on https://github.com/mydumper/mydumper/issues/860

I will tag this as duplicate.

**Comment by davidducos** [comment] 2022-11-01 15:41
Can you execute this on both databases:
select table_name,INDEX_NAME,SEQ_IN_INDEX,COLUMN_NAME from information_schema.STATISTICS WHERE table_schema='`<database>`' AND table_name='`<table>`';

With the right `<database>` and `<table>` values?

**Comment by davidducos** [comment] 2022-11-03 12:16
Definitely this is a duplicate of #860, sorry for the back and forth...

**Comment by davidducos** [comment] 2022-11-03 21:00
It is still not working properly

**Comment by davidducos** [comment] 2022-11-14 19:57
@fazi1058 please, share a test case so I can work on this before the next release.

**Closed** 2022-11-18 14:33 UTC
Labels: bug, duplicate, test case needed
