### ISSUE TITLE
[BUG] Blob data dumped from two different servers has differences

### ISSUE THREAD

**Issue by wodin** [mydumper/mydumper#568] opened 2022-02-02 09:02 UTC
## Description
I dumped a table containing some binary data in a blob column on two different servers using the same mydumper version with the same parameters. The output from one of the servers has extra backslash characters in the binary data.

I want to rsync the dumped data, so this difference will cause rsync to transfer more data than necessary.

If I use `mysqldump --hex-blob` then the output matches exactly. Is there something similar to `--hex-blob` or some other way to ensure the output from the two databases is in the same format?

## Command executed
Command executed:
```
mydumper --outputdir=./test \
    --rows=100000 \
    --compress \
    --threads=4 \
    --compress-protocol \
    --trx-consistency-only \
    --order-by-primary \
    --regex '^db\.table$' \
    --tz-utc \
    -L test.log
```
## Versions
* mydumper 0.11.5, built against MySQL 5.7.26-29 (running against a MySQL 5.5 database)
* mydumper 0.11.5, built against MySQL 5.7.33-36 (running against a MySQL 5.6 database)

## Expected behavior
I expected the output of the blob data to be the same.

## Log
This does not seem to be applicable

## Backup
All the expected files are produced. It's just the binary data that is slightly different

## Environment (please complete the following information):
 - OS version: Ubuntu 14.04.6 and Ubuntu 20.04.3
 - MyDumper version: mydumper 0.11.5, built against MySQL 5.7.26-29 and mydumper 0.11.5, built against MySQL 5.7.33-36

## Additional context
mysqldump has a --hex-blob format. Is there something similar for mydumper? Otherwise is there some other way to ensure the dumped binary data is the same in both cases?

**Comment by davidducos** [comment] 2022-02-02 13:19
Hi @wodin, is it possible for you to develop a test case? I will be installing a MySQL 5.5 on my end to reproduce the issue and see what is the best approach to solve it.

**Comment by wodin** [comment] 2022-02-03 07:25
I'll see what I can do. I have since noticed that mysqldump behaves similarly.
I tried compiling the client library from MySQL 5.7 and that did not seem to make a difference, but I did not recompile mydumper, so I'm not sure if mydumper was using the upgraded library.

**Comment by davidducos** [comment] 2022-02-14 19:30
Hi @wodin, I was not able to reproduce your issue. 
I tested on:
```
Server version:		5.5.62-38.14 Percona Server (GPL), Release 38.14, Revision 7e0e1cc
```
And I got this in the file, which is the same that I got from 5.7:
```
INSERT INTO `table` VALUES(1,"adfasd\nadsfasdf\nadf\nasdfa\n")
```
Please, provide a full test case, including versions of database server.

**Comment by davidducos** [comment] 2022-05-24 20:01
No test case provided, closing

**Closed by davidducos** 2022-05-24 20:01 UTC
Labels: bug, incomplete
