### ISSUE TITLE
[BUG]myloader stalls

### ISSUE THREAD

**Issue by aloks2019** [mydumper/mydumper#788] opened 2022-07-31 02:47 UTC
**Describe the bug**
I stared a restore using myloader and it could not start restore for 2 days. Back dir has 30million files. 

What mydumper and myloader version has been used?
0.12.1

I don’t have any logs to share. I saw that there were connections in database but all of them were in SLEEP state.
However, when we started restore using version9.5 that started automatically but for that we had to take backup again using mydumper 9.5.
We started restore in background using “screen”.

**Comment by afergadis** [comment] 2022-08-14 16:03
Same problem here.
myloader version: `myloader 0.12.5-3, built against MySQL 5.7.38-41`

I have 30 tables with a total data of 322GB. The process stalled after loading about 3.1GB in 4 tables. The command I use is:

`myloader -d /path/to/export/ --host=127.0.0.1 --user=root --innodb-optimize-keys --disable-redo-log --compress-protocol --verbose 3`

**Comment by davidducos** [comment] 2022-08-14 16:06
Hello,we are going to fix this bug after implementing #728.

**Comment by davidducos** [comment] 2022-08-14 21:47
BTW, this is a duplicate of #719

**Closed** 2022-08-29 13:52 UTC
Labels: bug, duplicate, Waiting pull request
