### ISSUE TITLE
Could we pass on the compression level via -exec-per-thread="/usr/bin/gzip --fast" --exec-per-thread-extension=".gz"

### ISSUE THREAD

**Issue by VMEMachuca** [mydumper/mydumper#1281] opened 2023-08-30 16:46 UTC
**Describe the bug**
mydumper0.14.5-3, built against MySQL 5.7.42-46 with SSL support with GZIP trying to pass on the gzip compression level -1,--fast" along with --exec-per-thread-extension=".gz"

** (mydumper:26302): CRITICAL **: 09:37:22.362: option parsing failed: Unknown option --fast", try --help

Getting 

**To Reproduce**
Command executed:
/perfshared/users/victor.machuca/el7.x86_64/mydumper-0.14.5/usr/bin/mydumper --user=perfdev --password=***** --host=s-50wrhh2.sys.az1.eng.pdx.wd --port=3306 --database=super_sb2 --outputdir=/data/exports/perf-exports/whopper/super_sb2.Save.20230830_0915.xar.super_sb2.tempdir/wdx.D_Dir-00 --less-locking --build-empty-files --trx-consistency-only --events --routines --triggers --compress --logfile=/perfshared/software/wmu/logs/mydumper.1693413441240.log --verbose=3 --threads=30 --rows=500000 --long-query-guard=86400 --exec-per-thread="/usr/bin/gzip --fast" --exec-per-thread-extension=".gz"

What mydumper and myloader version has been used?

0.14.5-3

**Expected behavior**
To honor the compression level we need

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
/perfshared/users/victor.machuca/el7.x86_64/mydumper-0.14.5/usr/bin/mydumper --user=perfdev --password=***** --host=s-50wrhh2.sys.az1.eng.pdx.wd --port=3306 --database=super_sb2 --outputdir=/data/exports/perf-exports/whopper/super_sb2.Save.20230830_0915.xar.super_sb2.tempdir/wdx.D_Dir-00 --less-locking --build-empty-files --trx-consistency-only --events --routines --triggers --compress --logfile=/perfshared/software/wmu/logs/mydumper.1693413441240.log --verbose=3 --threads=30 --rows=500000 --long-query-guard=86400 --exec-per-thread="/usr/bin/gzip --fast" --exec-per-thread-extension=".gz"

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9,]
 - MyDumper version: [ mydumper --version ]

**Additional context**
I tried similar command using zstd and it honored my flags

**Comment by VMEMachuca** [comment] 2023-08-30 17:33
I tried with mydumper 15.4-2 same results

**Comment by davidducos** [comment] 2023-08-30 18:34
Hi @VMEMachuca,
I think that your shell is removing the double-quoutes that enclose `/usr/bin/gzip --fast` which was the only way to reproduce your issue:
```
[root@mydumper1 ~/issue_1281/mydumper]# rm -rf data; ./mydumper -B sbtest --exec-per-thread=/usr/bin/gzip --fast --exec-per-thread-extension=".gz" -o data -v 3 --rows=500000

** (mydumper:17082): CRITICAL **: 18:32:29.130: option parsing failed: Unknown option --fast, try --help
```

**Comment by VMEMachuca** [comment] 2023-08-30 19:49
Not sure it is the case, since when I used zstd it honored all the way

**Comment by davidducos** [comment] 2023-08-30 19:51
Hi @VMEMachuca,
In order to be able to help you, I will need evidence as I was not able to reproduce your issue.

**Comment by davidducos** [comment] 2023-10-24 19:46
Closing as we need feedback to proceed.

**Closed by davidducos** 2023-10-24 19:46 UTC
Labels: bug, invalid
