### ISSUE TITLE
[BUG] mydumper dump failed when use `-- rows`

### ISSUE THREAD

**Issue by huangyan203316** [mydumper/mydumper#495] opened 2021-11-29 03:43 UTC
**Describe the bug**
mydumper 0.11.3 
I have a table with 2200 rows and the primary key is between `9131434967041` to `15655772094465`
it works fine in 0.10.8

**To Reproduce**
Command executed:
mydumper --host 127.0.0.1 --port 3306 --user root --password xxxxxxx   -B production_contest_exam --rows 2000 --verbose 3

**Logs**
```
** Message: 11:30:00.988: Empty table production_contest_exam.test_data
** Message: 11:30:00.988: Thread 2 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138007967041 AND `id` < 9138008967041)
** Message: 11:30:00.988: Empty table production_contest_exam.test_data
** Message: 11:30:00.988: Thread 4 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138008967041 AND `id` < 9138009967041)
** Message: 11:30:00.989: Empty table production_contest_exam.test_data
** Message: 11:30:00.990: Thread 2 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138009967041 AND `id` < 9138010967041)
** Message: 11:30:00.990: Empty table production_contest_exam.test_data
** Message: 11:30:00.990: Thread 1 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138010967041 AND `id` < 9138011967041)
** Message: 11:30:00.991: Empty table production_contest_exam.test_data
** Message: 11:30:00.991: Thread 2 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138011967041 AND `id` < 9138012967041)
** Message: 11:30:00.992: Empty table production_contest_exam.test_data
** Message: 11:30:00.992: Thread 4 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138012967041 AND `id` < 9138013967041)
** Message: 11:30:00.994: Empty table production_contest_exam.test_data
** Message: 11:30:00.995: Thread 2 dumping data for `production_contest_exam`.`test_data` WHERE (`id` >= 9138013967041 AND `id` < 9138014967041)
** Message: 11:30:00.996: Empty table production_contest_exam.test_data
Killed
```

**Comment by davidducos** [comment] 2021-11-29 03:55
Hi @huangyan203316, there is a know error which is going to be fixed in the next release. The problem is the amount of jobs that are being created. You must to increase the value in --rows to force the heuristic to use a larger chunk which reduces the amount of jobs created.

**Closed** 2021-12-10 20:09 UTC
Labels: bug, duplicate
