### ISSUE TITLE
[BUG] Any use of JSON_TABLE in the view get error in mydumper

### ISSUE THREAD

**Issue by pionar** [mydumper/mydumper#1699] opened 2024-12-17 13:47 UTC
**Describe the bug**
Any use of JSON_TABLE in the view get error in mydumper

`[ERROR] - Error dumping schemas (dev.helper_view_2): This version of MySQL doesn't yet support 'SHOW CREATE VIEW on a view that references a non-existent table and a table function.'`

manually running the query SHOW CREATE VIEW dev.helper_view_2 returns the correct result with no errors. 

**To Reproduce**
Command executed:
mydumper --host 127.0.0.1 --user user --password pass --rows=100000 --debug --trx-consistency-only --triggers --routines --events --build-empty-files --outputdir /backup/db_dev/ --threads 2 --compress -v 3

* myloader with all the parameters
myloader -u user -p pass --directory /backup/db_dev/--source-db dev --overwrite-tables --innodb-optimize-keys --verbose 3 --serialized-table-creation --fifodir=/tmp/bk

mydumper and myloader version:
v0.16.5-1, built against MySQL 8.0.36-28 with SSL support

mysql version:
8.4.1

**Log**
2024-12-13 06:33:12 [ERROR] - Error dumping schemas (dev.helper_view_2): This version of MySQL doesn't yet support 'SHOW CREATE VIEW on a view that references a non-existent table and a table function.'

**Environment:**
 - OS version: Ubuntu 22.04
 - MyDumper version: v0.16.5-1
 - Mysql 8.4.1

**Comment by davidducos** [comment] 2024-12-17 14:19
Hi @pionar,
Can you share a use case? as I was not able to reproduce it with:
```
CREATE DATABASE test;
create view test.david as
SELECT *
FROM
  JSON_TABLE(
    '[{"a": 1, "b": [11,111]}, {"a": 2, "b": [22,222]}]',
    '$[*]' COLUMNS(
        a INT PATH '$.a',
        NESTED PATH '$.b[*]' COLUMNS (b1 INT PATH '$'),
        NESTED PATH '$.b[*]' COLUMNS (b2 INT PATH '$')
    )
) AS jt;
```
I got this log:
```
circleci@f7116bec80a9:~/issue_options/mydumper$ ./mydumper -B test -v 3 -o data --clear
** Message: 14:16:26.931: MyDumper backup version: 0.17.0-1
** Message: 14:16:26.936: Config file loaded
** Message: 14:16:26.936: Using 4 dumper threads
** Message: 14:16:26.986: Connection via default library settings:
	Host: 172.17.0.8
** Message: 14:16:26.989: Connected to MySQL 8.4.1
** Message: 14:16:26.994: Started dump at: 2024-12-17 14:16:26
** Message: 14:16:26.994: Acquiring DDL lock
** Message: 14:16:26.994: LOCK INSTANCE FOR BACKUP: OK
** Message: 14:16:26.994: Acquiring Global lock
** Message: 14:16:26.994: FLUSH NO_WRITE_TO_BINLOG TABLES: OK
** Message: 14:16:26.994: FLUSH TABLES WITH READ LOCK: OK
** Message: 14:16:26.996: Creating workers
** Message: 14:16:26.996: Starting to enqueue non-transactional tables
** Message: 14:16:27.000: Thread 1: connected using MySQL connection ID 10
** Message: 14:16:27.000: Thread 4: connected using MySQL connection ID 13
** Message: 14:16:27.000: Thread 3: connected using MySQL connection ID 11
** Message: 14:16:27.000: Thread 2: connected using MySQL connection ID 12
** Message: 14:16:27.004: Thread 2: Creating Jobs
** Message: 14:16:27.004: Thread 4: Creating Jobs
** Message: 14:16:27.004: Thread 1: Creating Jobs
** Message: 14:16:27.004: Thread 3: Creating Jobs
** Message: 14:16:27.004: Waiting database finish
** Message: 14:16:27.004: Thread 4: dumping db information for `test`
** Message: 14:16:27.004: Written master status
** Message: 14:16:27.006: Thread 3: Processing Schema jobs
** Message: 14:16:27.006: Thread 2: Processing Schema jobs
** Message: 14:16:27.006: Thread 4: Processing Schema jobs
** Message: 14:16:27.006: Thread 3: dumping schema create for `test`
** Message: 14:16:27.008: Thread 1: Processing Schema jobs
** Message: 14:16:27.008: Shutdown jobs for less locking enqueued
** Message: 14:16:27.008: Thread 2: Schema jobs are done, Starting exporting data for Non-Transactional tables
** Message: 14:16:27.008: Thread 1: Schema jobs are done, Starting exporting data for Non-Transactional tables
** Message: 14:16:27.008: Thread 4: Schema jobs are done, Starting exporting data for Non-Transactional tables
** Message: 14:16:27.008: Thread 3: Schema jobs are done, Starting exporting data for Non-Transactional tables
** Message: 14:16:27.008: Enqueuing of non-transactional tables completed
** Message: 14:16:27.008: Starting to enqueue transactional tables
** Message: 14:16:27.008: Thread 4: Non-Transactional tables are done, Starting exporting data for Transactional tables
** Message: 14:16:27.008: Thread 3: Non-Transactional tables are done, Starting exporting data for Transactional tables
** Message: 14:16:27.008: Thread 2: Non-Transactional tables are done, Starting exporting data for Transactional tables
** Message: 14:16:27.008: Thread 1: Non-Transactional tables are done, Starting exporting data for Transactional tables
** Message: 14:16:27.008: Non-InnoDB dump complete, releasing global locks
** Message: 14:16:27.008: Enqueuing of transactional tables completed
** Message: 14:16:27.008: Thread 2: Processing remaining objects jobs
** Message: 14:16:27.008: Thread 1: Processing remaining objects jobs
** Message: 14:16:27.008: Thread 4: Processing remaining objects jobs
** Message: 14:16:27.008: Thread 3: Processing remaining objects jobs
** Message: 14:16:27.008: Thread 2: dumping view for `test`.`david`
** Message: 14:16:27.008: UNLOCK TABLES: OK
** Message: 14:16:27.008: Global locks released
** Message: 14:16:27.008: Thread 1: Shutting down
** Message: 14:16:27.009: Thread 3: Shutting down
** Message: 14:16:27.009: Waiting threads to complete
** Message: 14:16:27.009: Thread 4: Shutting down
** Message: 14:16:27.009: Thread 2: Shutting down
** Message: 14:16:27.020: Releasing DDL lock
** Message: 14:16:27.020: UNLOCK INSTANCE: OK
** Message: 14:16:27.020: Queue count: 0 0 0 0 0
** Message: 14:16:27.020: Main connection closed
** Message: 14:16:27.020: Finished dump at: 2024-12-17 14:16:27
```

**Comment by Thotep** [comment] 2024-12-17 22:41
I am stuck with this issue as well. Here's the full test database dump:
[mydumper_test.sql.txt](https://github.com/user-attachments/files/18172116/mydumper_test.sql.txt)

Steps to reproduce:
1. Create an SQL function (I created a dummy `LOWERCASE` function, which returns a lowercased string for a given string).
2. Create `view_1` that uses this function.
3. Create `view_2` which selects data from `view_1` AND uses the `JSON_TABLE` function to extract any JSON data.

Result:
```[ERROR] - Error dumping schemas (mydumper_test.view_2): This version of MySQL doesn't yet support 'SHOW CREATE VIEW on a view that references a non-existent table and a table function.'```

If you remove the function usage from the first view's definition in step 2, everything works correctly.

**Comment by Thotep** [comment] 2024-12-18 13:39
Thanks for pointing me in the right direction, this is actually a permission issue. Backup fails if the backup user doesn't have `EXECUTE` rights to this function on this database (because `SHOW CREATE VIEW mydumper_test.helper_view_2;` fails with the error above).
A quick and lazy solution would be to add execute rights to the backup user, but I think that a proper solution should be to change the current mydumper's mechanism of dumping views. You can avoid `SHOW CREATE VIEW` and get the view definition from `information_schema`, like so:
```SELECT * FROM information_schema.views WHERE table_schema = 'mydumper_test';```
This does not require EXECUTE rights for teh backup user.

**Comment by davidducos** [comment] 2024-12-18 14:32
Hi @Thotep,

Nice to hear that you were able to solve it! hope this also helps @pionar.

As users, I'm not sure why MySQL requires EXECUTE when we only want to do a SHOW CREATE VIEW. I don't know if it is a bug or it was on purpose. Anyway, I created this [bug on MySQL](https://bugs.mysql.com/bug.php?id=117014) to be sure about it.

About changing the code to SELECT the information_schema, we could end up in the same issue if the privileges are not ok. You can argue that we are performing SELECT over information_schema to get other information, but those scenarios can be avoided. 
On the other hand, SHOW CREATE VIEW returns a SQL statement based on how you configure the connection to the database, like SQL_MODE, character_set, etc. if we start to use a SELECT over information_schema, that responsibility will rely on MyDumper. That is why we are not going to implement it and not even mysqldump does it.

**Comment by davidducos** [comment] 2024-12-19 11:32
Hi @pionar / @Thotep ,

I'm closing this issue now as MySQL confirmed the bug. There is nothing else that we can do on our end.

**Closed by davidducos** 2024-12-19 11:32 UTC
Labels: help wanted, Invalid
