### ISSUE TITLE
[BUG] Please provide builds for Ubuntu 22.04 LTS/Jammy (OpenSSL v3+)

### ISSUE THREAD

**Issue by raoulbhatia** [mydumper/mydumper#718] opened 2022-06-09 20:34 UTC
**Describe the bug**
Ubuntu 22.04 LTS/Jammy ships with OpenSSL 3+.
The current builds do not work with this OpenSSL verison.

**To Reproduce**
Command executed:
* `mydumper`
* `myloader`

What mydumper and myloader version has been used?
0.12.3-3 via mydumper_0.12.3-3-zstd.bullseye_amd64.deb

**Expected behavior**
`mydumper` is starting.

**Log**
```
$ mydumper
mydumper: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**How to repeat**

1. Install Ubuntu 22.04 LTS/Jammy
2. Install mydumper Debian package from https://github.com/mydumper/mydumper/releases
3. Run `mydumper`

**Environment (please complete the following information):**
 - OS version: Ubuntu 22.04 LTS/Jammy
 - MyDumper version: 0.12.3-3 via mydumper_0.12.3-3-zstd.bullseye_amd64.deb

**Comment by davidducos** [comment] 2022-06-20 12:38
There are not a package for Jammy yet, as we need to wait until MySQL, MariaDB and Percona has an official package for it.

**Comment by xopez** [comment] 2022-08-19 12:05
MySQL and MariaDB is officially available for Ubuntu 22 (Jammy).
Only Percona hasn't released a new build.

**Comment by davidducos** [comment] 2022-08-19 13:30
Hi @xopez,
Thanks for the info!
[Release 0.12.7-1](https://github.com/mydumper/mydumper/milestone/25) is scheduled for September 05, 2022, and only 28% is completed and 45 issues on the queue. I can't promise that it will be for next release.

**Comment by davidducos** [comment] 2022-08-19 13:31
duplicate of https://github.com/mydumper/mydumper/issues/690

**Comment by xopez** [comment] 2022-08-19 13:32
No problem. There is no need rush, I just felt I should tell it since I didn't saw how well you are informed about new SQL Versions which depends on new OS.

**Comment by str** [comment] 2022-08-28 16:43
duplicated from #690

**Closed** 2022-09-14 14:56 UTC
Labels: duplicate, enhancement, Waiting pull request
