### ISSUE TITLE
[BUG] can not dump db with chinese db name

### ISSUE THREAD

**Issue by dongdongvs6** [mydumper/mydumper#1232] opened 2023-07-31 09:50 UTC
**Describe the bug**
if I have database like folows:
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| 测试               |
| mysql              |
| performance_schema |
+--------------------+

I can not finish the dump , because the failure:
mydumper -u root -p xx -S /tmp/mysql.sock -B 测试 --verbose=3
** Message: 16:41:56.032: MyDumper backup version: 0.15.1-1

** (mydumper:808392): CRITICAL **: 16:41:58.039: Error connection to database: Unknown database '测试'

**To Reproduce**
mydumper -u root -p xx -S /tmp/mysql.sock -B 测试 --verbose=3

What mydumper and myloader version has been used?
//  0.15.1-1

**Expected behavior**
I have found the reason , m_connect function should add character set 
void m_connect(MYSQL *conn, gchar *schema){
  configure_connection(conn);
  if (!mysql_real_connect(conn, hostname, username, password, schema, port,
                          socket_path, 0)) {
    m_critical("Error connection to database: %s", mysql_error(conn));
  }
  ...
}

**should  change to:**
void m_connect(MYSQL *conn, gchar *schema){
  configure_connection(conn);

  // it is very important to set character
  **mysql_set_character_set(conn, "utf8mb4");**

  if (!mysql_real_connect(conn, hostname, username, password, schema, port,
                          socket_path, 0)) {
    m_critical("Error connection to database: %s", mysql_error(conn));
  }
  ...
}

**Environment (please complete the following information):**
 // any linux environment

**Additional context**
//  add character set before real connect, follow the  *Expected behavior* description.

**Comment by dongdongvs6** [comment] 2023-07-31 09:54
void m_connect(MYSQL *conn, gchar *schema){
configure_connection(conn);

// add character set  here
**mysql_set_character_set(conn, "utf8mb4");**

if (!mysql_real_connect(conn, hostname, username, password, schema, port,
socket_path, 0)) {
m_critical("Error connection to database: %s", mysql_error(conn));
}
...

**Comment by davidducos** [comment] 2023-07-31 13:16
Hi @dongdongvs6,
I have 2 options for you:
1- You can use "--setnames utf8mb4" as parameter, which is not the best option because the backup will add the set names to utf8mb4 and it is preferable to use binary, but that is up to you.
2- Create a file mydumper.cnf with:
```
[mydumper_session_variables]
character_set_client=utf8mb4
character_set_connection=utf8mb4
character_set_results=utf8mb4
```
And then use the `--defaults-extra-file=mydumper.cnf` to use also those variables. 

I test both, please let me know if you have any question, if not, just close the issue. Thank you for using MyDumper!
Cheers

**Comment by dongdongvs6** [comment] 2023-08-02 03:56
sorry for late reply， it is not OK :

~ # mydumper -u root -p XX -S /mysql.sock -B 测试 **--defaults-extra-file=mydumper.cnf**

** (mydumper:2624504): CRITICAL **: 11:55:10.898: Error connection to database: Unknown database '测试'

 ~ # mydumper -u root -p XX  -S //mysql.sock -B 测试 **--set-names utf8mb4**

** (mydumper:2624771): CRITICAL **: 11:55:15.857: Error connection to database: Unknown database '测试'

**Comment by davidducos** [comment] 2023-08-02 13:21
The only way that I was able to reproduce your issue, was setting the connection to latin1 prior connection. Anyways, I'm removing schema during connection as it is not needed because the threads that uses the -B schema are checking if they are connected to the right database and the ones that doesn't use the -B schema... doesn't need it! 
You will still need to use --defaults-extra-file as, as I earlier in this comment, seems that your database is in latin1 or there is anything else that is changing the connection. This means that you might have errors, but not this one. I will be releasing v0.15.1-2 later today.

**Closed** 2023-08-02 14:40 UTC
Labels: help wanted, invalid

**Comment by dongdongvs6** [comment] 2023-08-04 09:29
use the latest v0.15.1-3, not OK . try to follow method:
CREATE DATABASE `测试` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

use  `测试` ；

CREATE TABLE `测试` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci；

insert into  `测试`  values(1, 'AAAAA');

Then， use dumper:

mydumper -u root -p xx -S /mysql.sock --defaults-extra-file mydumper.cnf

**dump is normal finish , but export-XX  does not include  `测试`。**

**Comment by dongdongvs6** [comment] 2023-08-04 09:41
checked agained , the schema name renamed, it is ok now:
mydumper_0.mydumper_0.00000.sql   mydumper_0.mydumper_0-schema.sql  mydumper_0-schema-create.sql      mydumper_0-schema-triggers.sql

**Comment by davidducos** [comment] 2023-08-04 11:49
Hi @dongdongvs6, love to hear that it is working now!! yes, we are renaming when databases doesn't meet internal criteria to avoid parsing issues.
