### ISSUE TITLE
[BUG] mydumper lock indefinitively

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#539] opened 2022-01-06 08:56 UTC
**Describe the bug**

Mydumper is launched and stay locked in doing nothing for days.

mydumper --defaults-file=/etc/mysql/debian.cnf --triggers --events --routines --compress --logfile=/var/backups/mysql/sauvergarde.2021-12-30-23h04.log --outputdir=/var/backups/mysql/2021-12-30-23h04 --regex ^(?!(test\.|sys\.)) --use-savepoints --less-locking --long-query-guard 120 --kill-long-queries --verbose 3

disk is not full at all so no issue there too.

**To Reproduce**
root      32036  0.0  0.1 656092 15020 ?        Sl    2021   0:56      \_ mydumper --defaults-file=/etc/mysql/debian.cnf --triggers --events --routines --compress --logfile=/var/backups/mysql/sauvergarde.2021-12-30-23h04.log --outputdir=/var/backups/mysql/2021-12-30-23h04 --regex ^(?!(test\.|sys\.)) --use-savepoints --less-locking --long-query-guard 120 --kill-long-queries --verbose 3

the issue is that it does not lock all the time it just randomly do that. Most of the time the daily dump works fine. Then all of a sudden it just lock forever. Never had the same issue with mysqlsdump used before.

**Expected behavior**
dump the databases and end normaly :)

**Log**
logs attached, ends with nothing
[mydumperlock.log](https://github.com/mydumper/mydumper/files/7820426/mydumperlock.log)

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough
[mydumperlockdir.log](https://github.com/mydumper/mydumper/files/7820490/mydumperlockdir.log)

**Environment (please complete the following information):**
 - OS version: Debian GNU/Linux 9.13 (stretch)
 - MyDumper version: mydumper 0.11.5, built against MySQL 5.7.35-38

**Additional context**

: cat  /var/backups/mysql/2021-12-30-23h04/metadata.partial
Started dump at: 2021-12-30 23:04:22

still locked on january 6

COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF       NODE NAME
mydumper 32036 root  cwd    DIR              9,126     4096          2 /
mydumper 32036 root  rtd    DIR              9,126     4096          2 /
mydumper 32036 root  txt    REG              9,126  4443312    5112644 /usr/bin/mydumper
mydumper 32036 root  mem    REG              9,126    47632    4962706 /lib/x86_64-linux-gnu/libnss_files-2.24.so
mydumper 32036 root  mem    REG              9,126    19008    4962733 /lib/x86_64-linux-gnu/libuuid.so.1.3.0
mydumper 32036 root  mem    REG              9,126   283464    4962665 /lib/x86_64-linux-gnu/libblkid.so.1.1.0
mydumper 32036 root  mem    REG              9,126    35296    4980476 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
mydumper 32036 root  mem    REG              9,126   313096    4962697 /lib/x86_64-linux-gnu/libmount.so.1.1.0
mydumper 32036 root  mem    REG              9,126    84848    4962719 /lib/x86_64-linux-gnu/libresolv-2.24.so
mydumper 32036 root  mem    REG              9,126   155400    4962722 /lib/x86_64-linux-gnu/libselinux.so.1
mydumper 32036 root  mem    REG              9,126    14656    4980487 /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.5000.3
mydumper 32036 root  mem    REG              9,126  1689360    4962668 /lib/x86_64-linux-gnu/libc-2.24.so
mydumper 32036 root  mem    REG              9,126    92584    4962683 /lib/x86_64-linux-gnu/libgcc_s.so.1
mydumper 32036 root  mem    REG              9,126  1566168    4980598 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
mydumper 32036 root  mem    REG              9,126   465232    4962714 /lib/x86_64-linux-gnu/libpcre.so.3.13.3
mydumper 32036 root  mem    REG              9,126   339000    4980490 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5000.3
mydumper 32036 root  mem    REG              9,126  1656904    4980486 /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5000.3
mydumper 32036 root  mem    REG              9,126     6160    4980494 /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.5000.3
mydumper 32036 root  mem    REG              9,126  1127520    4962685 /lib/x86_64-linux-gnu/libglib-2.0.so.0.5000.3
mydumper 32036 root  mem    REG              9,126    14640    4962677 /lib/x86_64-linux-gnu/libdl-2.24.so
mydumper 32036 root  mem    REG              9,126  2720032    5111930 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
mydumper 32036 root  mem    REG              9,126   442984    5113884 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
mydumper 32036 root  mem    REG              9,126    26768    4980450 /usr/lib/x86_64-linux-gnu/libatomic.so.1.2.0
mydumper 32036 root  mem    REG              9,126    31744    4962720 /lib/x86_64-linux-gnu/librt-2.24.so
mydumper 32036 root  mem    REG              9,126  1063328    4962694 /lib/x86_64-linux-gnu/libm-2.24.so
mydumper 32036 root  mem    REG              9,126   105088    4962735 /lib/x86_64-linux-gnu/libz.so.1.2.8
mydumper 32036 root  mem    REG              9,126   135440    4962717 /lib/x86_64-linux-gnu/libpthread-2.24.so
mydumper 32036 root  mem    REG              9,126   153288    4962656 /lib/x86_64-linux-gnu/ld-2.24.so
mydumper 32036 root  mem    REG              9,126    26258    5113079 /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
mydumper 32036 root    0r  FIFO               0,10      0t0 2947190822 pipe
mydumper 32036 root    1w  FIFO               0,10      0t0 2947190823 pipe
mydumper 32036 root    2w  FIFO               0,10      0t0 2947190824 pipe
mydumper 32036 root    3w   REG              9,126    33324    5249837 /var/backups/mysql/sauvergarde.2021-12-30-23h04.log
mydumper 32036 root    5w   REG              9,126       37    6161187 /var/backups/mysql/2021-12-30-23h04/metadata.partial
mydumper 32036 root    8u  unix 0xffff9a1f7da9d800      0t0 2947188454 type=STREAM
mydumper 32036 root   10u  unix 0xffff9a1f7da9b000      0t0 2947188456 type=STREAM
mydumper 32036 root   11u  unix 0xffff9a1f7da9cc00      0t0 2947188457 type=STREAM
mydumper 32036 root   12u  unix 0xffff9a1f7da9ac00      0t0 2947188458 type=STREAM
mydumper 32036 root   13u  unix 0xffff9a1f7da9a800      0t0 2947188459 type=STREAM

[~]: strace -p 32036
strace: Process 32036 attached
futex(0x7f9442ed19d0, FUTEX_WAIT, 32039, NULL

no process running in mysql
mysql> show full processlist;
+---------+------------------+-----------+------+---------+--------+----------+-----------------------+-----------+---------------+
| Id      | User             | Host      | db   | Command | Time   | State    | Info                  | Rows_sent | Rows_examined |
+---------+------------------+-----------+------+---------+--------+----------+-----------------------+-----------+---------------+
| 1483804 | debian-sys-maint | localhost | sys  | Sleep   | 555666 |          | NULL                  |         0 |             0 |
| 1483806 | debian-sys-maint | localhost | NULL | Sleep   | 555666 |          | NULL                  |         0 |             0 |
| 1483807 | debian-sys-maint | localhost | NULL | Sleep   | 555666 |          | NULL                  |         0 |             0 |
| 1483808 | debian-sys-maint | localhost | NULL | Sleep   | 555666 |          | NULL                  |         0 |             0 |
| 1483809 | debian-sys-maint | localhost | NULL | Sleep   | 555665 |          | NULL                  |         0 |             0 |
| 2846774 | debian-sys-maint | localhost | NULL | Query   |      0 | starting | show full processlist |         0 |             0 |

no mysql log. seems 5 threads are locked.

Any ideas on what could cause this lockup

best regards,
Ghislain.

**Comment by aqueos** [comment] 2022-01-06 12:42
Hi David,

I use the percona mysql packages, on this particular one it is

ii  percona-server-server-5.7         5.7.36-39-1.stretch amd64        Percona Server database server binaries

this is
[~]: mysql -V
mysql  Ver 14.14 Distrib 5.7.36-39, for debian-linux-gnu (x86_64) using  7.0

**Comment by davidducos** [comment] 2022-01-06 14:01
@aqueos, 
Do you have non-innodb tables? If you only have innodb tables, then disable --less-locking and check again, as it might be related to less locking feature. I think that I found where could be the issue but it is really difficult to reproduce and create a test case.

**Comment by aqueos** [comment] 2022-01-06 14:35
most of the tabels here are in legacy myisam (yes i know), allmost no innodb here.

```
| engine             | tables | Lignes | Donnees | Idx   | Global | idxfrac |
+--------------------+--------+--------+---------+-------+--------+---------+
| MyISAM             |    109 | 17.12M | 2.71G   | 0.48G | 3.18G  |    0.18 |
| InnoDB             |     75 | 0.01M  | 0.00G   | 0.00G | 0.00G  |    0.19 |
| MEMORY             |     65 | NULL   | 0.00G   | 0.00G | 0.00G  |    NULL |
| CSV                |      2 | 0.00M  | 0.00G   | 0.00G | 0.00G  |    NULL |
| PERFORMANCE_SCHEMA |     87 | 1.46M  | 0.00G   | 0.00G | 0.00G  |    NULL |
| NULL               |    100 | NULL   | NULL    | NULL  | NULL   |    NULL |
```

yes its hard because it works allmost all the time i just had one lock here and there. It is not frequent at all :(
when i launch it on the command line it allways works but i dont launch it as often as the daily cron of course.

regards,
Ghislain.

**Comment by davidducos** [comment] 2022-01-07 14:02
@aqueos,
Can you check without --less-locking ?? or is it mandatory for you?

**Comment by fengbao123** [comment] 2022-01-13 08:14
I have the same problem，All threads are in sleep，And the memory of the mydumper process keeps increasing until the oom is triggered

OS version: CentOS Linux release 7.8.2003 (Core)  x86_64

mydumper -V
mydumper 0.11.5, built against MySQL 5.7.34-37

database:  Percona Server mysql  Ver 14.14 Distrib 5.7.25-28, for Linux (x86_64) using  6.2

```
 mydumper  -o /data1/backup -h 1xx.xx.xx -P 3306 -u root -p 'xxxxxx' -t 8 -r 100000 -c -G -E -R --trx-consistency-only --regex='^(?!(mysql|information_schema|performance_schema|test))' -v 3 -L /tmp/mydumper.log --less-locking
```


```
+--------+-------------+---------------------+---------------+---------+---------+-------+------+-----------+---------------+
| Id     | User        | Host                | db            | Command | Time    | State | Info | Rows_sent | Rows_examined |
+--------+-------------+---------------------+---------------+---------+---------+-------+------+-----------+---------------+
| 430158 | root        | 10.100.xx.xxx:60426 | NULL          | Sleep   |      81 |       | NULL |         1 |             0 |
| 430159 | root        | 10.100.xx.xxx:60428 | wordpress     | Sleep   |      81 |       | NULL |   1123958 |       1123958 |
| 430160 | root        | 10.100.xx.xxx:60430 | test1         | Sleep   |      81 |       | NULL |    121635 |        121635 |
| 430161 | root        | 10.100.xx.xxx:60432 | test          | Sleep   |      80 |       | NULL |        29 |            29 |
| 430162 | root        | 10.100.xx.xxx:60434 | maops         | Sleep   |      80 |       | NULL |      2753 |          2753 |
| 430163 | root        | 10.100.xx.xxx:60436 | mysql         | Sleep   |      80 |       | NULL |     19691 |         19691 |
| 430164 | root        | 10.100.xx.xxx:60438 | sap_wb        | Sleep   |      83 |       | NULL |    609152 |        609152 |
| 430165 | root        | 10.100.xx.xxx:60442 | xxl_job_prod  | Sleep   |      81 |       | NULL |     80927 |         80927 |
| 430166 | root        | 10.100.xx.xxx:60446 | sys           | Sleep   |      82 |       | NULL |    121635 |        121635 |
+--------+-------------+---------------------+---------------+---------+---------+-------+------+-----------+---------------+
```

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
30076 root      20   0   16.7g  16.0g   4652 R 100.3  6.4   2:11.91 mydumper 
```

**Comment by fengbao123** [comment] 2022-01-13 08:15
```
# strace -c -p 22372
strace: Process 22372 attached
^Cstrace: Process 22372 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.068421           0    132816           brk
------ ----------- ----------- --------- --------- ----------------
100.00    0.068421                132816           total
```

**Comment by fengbao123** [comment] 2022-01-13 08:37
With the same command, the backup of version mydumper-0.9.5-2.el7.x86_64.rpm is normal

**Comment by davidducos** [comment] 2022-01-13 09:03
Hi @aqueos , looks like you didn't see my comment. I asked you if you can execute the same command without --less-locking

**Comment by aqueos** [comment] 2022-01-13 09:26
hi david,

 Well the issue is that i cannot reproduce it at will. 
 It works most of the time with this --less-locking ,i can launch it and it works, i have the daily  cron that run successfully since my firts mail on this thread. So yes i can but it will not lock the dump as i cannot reproduce on purpose this issue. It happens from time to time on rare occasions :)

best regards,
Ghislain

**Comment by davidducos** [comment] 2022-01-20 13:08
Hi @aqueos, without a test case will be very difficult to know what is the issue. 
I will close this, but feel free to open at any time.

**Closed by davidducos** 2022-01-20 13:08 UTC
Labels: bug
