### ISSUE TITLE
Performance Drop : Performance change between versions - large data backup

### ISSUE THREAD

**Issue by datascience-dba** [mydumper/mydumper#910] opened 2022-11-18 15:18 UTC
I use mydumper and myloader to backup and restore DB's from mysql 5.7

During testing with new version I have noticed a big performance drop. It also seems as if the level of compression has been reduced. Please see below. Please let me know if there is anything I can change. I also have more test data to share if required.

** Duration 7hrs1min **
Version:
mydumper 0.9.5, built against MySQL 8.0.19
metadata file:
Started dump at: 2022-11-14 06:15:02
Finished dump at: 2022-11-14 13:16:39 
Backup size:
589G 

** Duration 14hrs45min **
Version:
mydumper0.13.0, built against MySQL 8.0.29 with SSL support with GZIP
metadata file:
Started dump at: 2022-11-17 15:49:39
Finished dump at: 2022-11-18 06:34:28 
Backup size:
655G 

Both servers are equally spec'ed
This is the same database. The backup was restored and then backed up again.

This is the backup command used:

mydumper --host=production_db
--user=username
--password=secret
--regex '^(?!(information_schema|innodb|mysql|performance_schema|sys|None))'
--outputdir=/backup/
--logfile=/backup/mydumper.log
--long-query-guard 300
--chunk-filesize=1000
--events
--routines
--triggers
--build-empty-files
--threads=8
--lock-all-tables
--compress
--verbose=3

**Comment by davidducos** [comment] 2022-11-18 17:47
Hi @datascience-dba 

Can you execute with --chunk-filesize=1000:100000:1000000 on v0.13.0-6 ?? And is it possible to provide the log of both executions?

**Comment by datascience-dba** [comment] 2022-11-18 17:51
Hi @davidducos ,

As always, thank you for the quick response.

Just to confirm - this is one parameter "--chunk-filesize=1000:100000:1000000" 

I will yes. I will collect the data over the weekend.

**Comment by davidducos** [comment] 2022-11-18 17:54
@datascience-dba Oh, no! I thought that was --rows, sorry! 
Doesn't make sense to me the performance drop as it should be doing a full table scan per table. Can you test with --rows= 1000:100000:1000000 ?

**Comment by datascience-dba** [comment] 2022-11-18 18:15
Sure. I will try it.

0.9.5 runs at between 1.8 and 2GB/min where 0.13.0-5 runs around 0.8-1.0 GB/min on the output.

**Comment by datascience-dba** [comment] 2022-11-19 12:14
While testing the dump as requested

The dump process got stuck in an endless loop and ended up only 
having 1 process show up in the processlist.

I eventually killed it.

Version used:
mydumper-0.13.0-6

Command and parameters:
/usr/bin/mydumper-0.13.0-6 --host=db_server_name --user=username --password=secret --regex '^(?!(information_schema|innodb|mysql|performance_schema|sys|None))' 
--outputdir=./ --logfile=/tmp/mydumper-0.13.0-6_parm_rows.log --long-query-guard 300 
--rows=1000:100000:1000000 
--events --routines --triggers --build-empty-files 
--threads=8 --lock-all-tables --compress --verbose=3


MySQL [(none)]> show create table `dbname`.`tab_name`\G
*************************** 1. row ***************************
       Table: tab_name
Create Table: CREATE TABLE `tab_name` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'Same as some_other_tab.id',
  `data` json NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `some_fk1` FOREIGN KEY (`id`) REFERENCES `some_other_tab` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.000 sec)

MySQL [(none)]> select count(1) from `dbname`.`tab_name`;
+----------+
| count(1) |
+----------+
|      264 |
+----------+
1 row in set (0.002 sec)

MySQL [(none)]> select round(sum(data_length+index_length)/1024) kb from information_schema.tables 
where table_name = 'tabname' and table_schema = 'dbname';
+------+
| kb   |
+------+
|  224 |
+------+
1 row in set (0.000 sec)


2022-11-19 11:35:39 [INFO] - Thread 4 dumping data for `dbname`.`tab_name`  WHERE ( 717077479883963615 < `id` AND `id` <= 717077479884963615)       into ./dbname.tab_name.00019.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 5 dumping data for `dbname`.`tab_name`  WHERE ( 695498533921222341 < `id` AND `id` <= 695498533922222341)       into ./dbname.tab_name.00014.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 3 dumping data for `dbname`.`tab_name`  WHERE ( 703477544529089962 < `id` AND `id` <= 703477544530089962)       into ./dbname.tab_name.00013.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 6 dumping data for `dbname`.`tab_name`  WHERE ( 718193950327243398 < `id` AND `id` <= 718193950328243398)       into ./dbname.tab_name.00011.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 1 dumping data for `dbname`.`tab_name`  WHERE ( 691726900721991691 < `id` AND `id` <= 691726900722991691)       into ./dbname.tab_name.00006.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 4 dumping data for `dbname`.`tab_name`  WHERE ( 717077479884963615 < `id` AND `id` <= 717077479885963615)       into ./dbname.tab_name.00019.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 2 dumping data for `dbname`.`tab_name`  WHERE ( 677039350492225988 < `id` AND `id` <= 677039350493225988)       into ./dbname.tab_name.00012.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 7 dumping data for `dbname`.`tab_name`  WHERE ( 672708152324876674 < `id` AND `id` <= 672708152325876674)       into ./dbname.tab_name.00024.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 3 dumping data for `dbname`.`tab_name`  WHERE ( 703477544530089962 < `id` AND `id` <= 703477544531089962)       into ./dbname.tab_name.00013.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 2 dumping data for `dbname`.`tab_name`  WHERE ( 677039350493225988 < `id` AND `id` <= 677039350494225988)       into ./dbname.tab_name.00012.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 6 dumping data for `dbname`.`tab_name`  WHERE ( 718193950328243398 < `id` AND `id` <= 718193950329243398)       into ./dbname.tab_name.00011.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 5 dumping data for `dbname`.`tab_name`  WHERE ( 695498533922222341 < `id` AND `id` <= 695498533923222341)       into ./dbname.tab_name.00014.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 3 dumping data for `dbname`.`tab_name`  WHERE ( 703477544531089962 < `id` AND `id` <= 703477544532089962)       into ./dbname.tab_name.00013.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 8 dumping data for `dbname`.`tab_name`  WHERE ( 724709517722626930 < `id` AND `id` <= 724709517723626930)       into ./dbname.tab_name.00007.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 1 dumping data for `dbname`.`tab_name`  WHERE ( 691726900722991691 < `id` AND `id` <= 691726900723991691)       into ./dbname.tab_name.00006.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 7 dumping data for `dbname`.`tab_name`  WHERE ( 672708152325876674 < `id` AND `id` <= 672708152326876674)       into ./dbname.tab_name.00024.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 6 dumping data for `dbname`.`tab_name`  WHERE ( 718193950329243398 < `id` AND `id` <= 718193950330243398)       into ./dbname.tab_name.00011.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 4 dumping data for `dbname`.`tab_name`  WHERE ( 717077479885963615 < `id` AND `id` <= 717077479886963615)       into ./dbname.tab_name.00019.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 5 dumping data for `dbname`.`tab_name`  WHERE ( 695498533923222341 < `id` AND `id` <= 695498533924222341)       into ./dbname.tab_name.00014.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 3 dumping data for `dbname`.`tab_name`  WHERE ( 703477544532089962 < `id` AND `id` <= 703477544533089962)       into ./dbname.tab_name.00013.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 2 dumping data for `dbname`.`tab_name`  WHERE ( 677039350494225988 < `id` AND `id` <= 677039350495225988)       into ./dbname.tab_name.00012.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 8 dumping data for `dbname`.`tab_name`  WHERE ( 724709517723626930 < `id` AND `id` <= 724709517724626930)       into ./dbname.tab_name.00007.sql.gz| Remaining jobs: 0
2022-11-19 11:35:39 [INFO] - Thread 7 dumping data for `dbname`.`tab_name`  WHERE ( 672708152326876674 < `id` AND `id` <= 672708152327876674)       into ./dbname.tab_name.00024.sql.gz| Remaining jobs: 0




prodks1# ls -l dbname.tab_name.000*
-rw-rw-r-- 1 mysql mysql 7673 Nov 19 11:23 dbname.tab_name.00000.sql.gz
-rw-rw-r-- 1 mysql mysql   20 Nov 19 11:23 dbname.tab_name.00001.sql.gz
-rw-rw-r-- 1 mysql mysql   20 Nov 19 11:23 dbname.tab_name.00002.sql.gz
-rw-rw-r-- 1 mysql mysql   20 Nov 19 11:24 dbname.tab_name.00003.sql.gz
-rw-rw-r-- 1 mysql mysql   20 Nov 19 11:23 dbname.tab_name.00004.sql.gz
-rw-rw-r-- 1 mysql mysql   20 Nov 19 11:24 dbname.tab_name.00005.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:23 dbname.tab_name.00006.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:23 dbname.tab_name.00007.sql.gz
-rw-rw-r-- 1 mysql mysql   20 Nov 19 11:23 dbname.tab_name.00008.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:23 dbname.tab_name.00011.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:23 dbname.tab_name.00012.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:24 dbname.tab_name.00013.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:24 dbname.tab_name.00014.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:24 dbname.tab_name.00019.sql.gz
-rw-rw-r-- 1 mysql mysql    0 Nov 19 11:23 dbname.tab_name.00024.sql.gz

**Comment by datascience-dba** [comment] 2022-11-19 12:23
mydumper 0.13.0-6
cat metadata.partial
Started dump at: 2022-11-19 10:38:29

Sat Nov 19 10:41:31 UTC 2022
1.2G    /data/backup/dbdump/prodks1/
Sat Nov 19 10:42:01 UTC 2022
1.4G    /data/backup/dbdump/prodks1/
Sat Nov 19 10:42:31 UTC 2022
1.6G    /data/backup/dbdump/prodks1/
Sat Nov 19 10:43:01 UTC 2022
1.8G    /data/backup/dbdump/prodks1/
rate=> 200MB/30s 6.67MB/s



mydumper 0.9.5
cat metadata.partial
Started dump at: 2022-11-19 10:44:25

Sat Nov 19 10:44:46 UTC 2022
270M    /data/backup/dbdump/prodks1/
Sat Nov 19 10:45:16 UTC 2022
667M    /data/backup/dbdump/prodks1/
Sat Nov 19 10:45:46 UTC 2022
1.1G    /data/backup/dbdump/prodks1/
Sat Nov 19 10:46:16 UTC 2022
1.6G    /data/backup/dbdump/prodks1/
Sat Nov 19 10:46:46 UTC 2022
2.3G    /data/backup/dbdump/prodks1/
rate=>+- 580MB/30s 19.3MB/s

**Comment by datascience-dba** [comment] 2022-11-19 12:25
mydumper 0.13.0-6
cat metadata.partial
Started dump at: 2022-11-19 10:38:29

Sat Nov 19 10:41:31 UTC 2022 1.2G
Sat Nov 19 10:42:01 UTC 2022 1.4G
Sat Nov 19 10:42:31 UTC 2022 1.6G
Sat Nov 19 10:43:01 UTC 2022 1.8G
rate=> 200MB/30s 6.67MB/s



mydumper 0.9.5
cat metadata.partial
Started dump at: 2022-11-19 10:44:25

Sat Nov 19 10:44:46 UTC 2022 270M
Sat Nov 19 10:45:16 UTC 2022 667M
Sat Nov 19 10:45:46 UTC 2022 1.1G
Sat Nov 19 10:46:16 UTC 2022 1.6G
Sat Nov 19 10:46:46 UTC 2022 2.3G
rate=>+- 580MB/30s 19.3MB/s

**Comment by davidducos** [comment] 2022-11-20 22:03
Hi @datascience-dba,
I have been thinking and working on this the WHOLE weekend... and finally got it... seems that we shouldn't use g_string_append_printf. If I changed this line https://github.com/mydumper/mydumper/blob/78bfe0346deca109034a522e6afb3770348a3b26/src/mydumper_write.c#L390 from:
```
    g_string_append_printf(statement_row,"%s", lines_terminated_by);
```
To:
```
    g_string_append_c(statement_row,'\n');
```
we get this timings with g_string_append_printf (2 executions to see difference in timings):
```
[root@mydumper1 mydumper]# rm -rf data; time ./mydumper -T myd_test.david -o data -v 3 -L test
real	0m4.588s
user	0m2.922s
sys	0m0.369s
[root@mydumper1 mydumper]# rm -rf data; time ./mydumper -T myd_test.david -o data -v 3 -L test
real	0m4.933s
user	0m3.128s
sys	0m0.349s
```
And this is with g_string_append_c:
```
[root@mydumper1 mydumper]# rm -rf data; time ./mydumper -T myd_test.david -o data -v 3 -L test
real	0m2.840s
user	0m1.780s
sys	0m0.259s
[root@mydumper1 mydumper]# rm -rf data; time ./mydumper -T myd_test.david -o data -v 3 -L test
real	0m2.915s
user	0m1.723s
sys	0m0.281s
```
Thank you for reporting this issue as this has been in the code since we implemented --load-data. I think that a lot of people will be happy that we can fix it. 
I will be creating the PR with my review and fix.

**Comment by datascience-dba** [comment] 2022-11-21 07:36
Good morning @davidducos .

This is good news indeed. I will run another test as soon as the PR is done. 
Thank you for doing this so quickly.

**Comment by anthosz** [comment] 2022-12-01 13:30
Hello,

I just reproduced also the issue with the last tag 0.13.1-1 (compared to 0.12).

A dump of 50GB take 40min with the v0.12 vs +1h20 for the v0.13 (I killed the process before it finish (dump was done at ~60% when I killed it)).

Best regards,

**Comment by davidducos** [comment] 2022-12-01 13:33
@anthosz you might have a misconfiguration that cause the performance drop. This particular issue has been solved. 
fyi, this issue was a mydumper execution without setting -r, if you are using -r, it is a different issue and I will need you to fill a new bug.

**Comment by anthosz** [comment] 2022-12-01 13:42
@davidducos thank you for the reactivity! 

I didn't use the -r

Here is the command:
`mydumper --no-schemas --threads 8 --exit-if-broken-table-found --defaults-file=${CONF} --disk-limits '500:800' --compress --trx-consistency-only --lock-all-tables --verbose 3 --outputdir ${PATH} --regex '^(?!([^\.]+.(aaa)?(table1|second)))'`

Excluding the time, I cannot explain why :/ (log are not really relevant in this situation)

It was done each time from the same server to the same DB (without any traffic on them, isolated)

**Comment by davidducos** [comment] 2022-12-01 13:48
@anthosz, I need both logs, from v0.12 and v0.13, for me are very useful.

**Comment by davidducos** [comment] 2023-03-27 20:43
@anthosz can you test with the latest version?

**Comment by anthosz** [comment] 2023-03-27 20:50
> @anthosz can you test with the latest prerelease?

Thank you for your feedback, will try to do it in the next days

**Comment by davidducos** [comment] 2023-04-21 12:40
@anthosz do you have any news? I would like to know if I can close this issue.

**Comment by anthosz** [comment] 2023-04-21 18:42
@davidducos I will try to check next week (using always the v0.12 right now)

**Comment by davidducos** [comment] 2023-05-18 19:59
Closing as we didn't receive any feedback

**Closed by davidducos** 2023-05-18 19:59 UTC
Labels: bug

**Comment by anthosz** [comment] 2023-08-14 11:03
Hello @davidducos ,

Sorry for the delay, didn't had time and using always the v0.12 at this time.

I just launched a new tentative with the v0.15, will keep you informed.

**Comment by anthosz** [comment] 2023-08-14 12:59
Confirmed, all ok with last version (import/dump time reduced too).
