### ISSUE TITLE
[BUG] Intermittent Segmentation Fault

### ISSUE THREAD

**Issue by billynoah** [mydumper/mydumper#1399] opened 2024-02-01 15:44 UTC
**Describe the bug**
I have a daily cron job that iterates over our production databases and dumps each one. Once every few days, we get a segmentation fault seemingly at random and one of the dumps ends up incomplete, e.g.,

> /root/.cron/daily.sh: line 37: 527923 Segmentation fault      (core dumped) mydumper --verbose=3 --logfile=/root/.cron/logs/${i}_$(date +\%F).log --compress=ZSTD --trx-consistency-only --threads=8 --chunk-filesize=512 --database=$i --outputdir=$DUMP_DIR

**To Reproduce**
Command executed:
```
i=ship_example.com
DUMP_DIR=/var/www/backups/daily/$(date +\%F)/$i
mkdir -p $DUMP_DIR
mydumper --verbose=3 --logfile=/root/.cron/logs/${i}_$(date +\%F).log --compress=ZSTD --trx-consistency-only --threads=8 --chunk-filesize=512 --database=$i --outputdir=$DUMP_DIR
```

What mydumper and myloader version has been used?
mydumper v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

**Expected behavior**
Not segmentation fault.

**Log**
[ship_example.com_2024-02-01.log](https://github.com/mydumper/mydumper/files/14127472/ship_example.com_2024-02-01.log)

**Backup**
[ship_example.com_2024-02-01_ls.txt](https://github.com/mydumper/mydumper/files/14127506/ship_example.com_2024-02-01_ls.txt)

**How to repeat**
This is difficult to consistently reproduce since it happens randomly. I'm not sure where and when to make a core dump as I'm only becoming aware of the crash the following day.

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-169-generic x86_64)
 - MyDumper version: mydumper v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

**Comment by davidducos** [comment] 2024-02-22 18:36
Hi @billynoah, is it possible for you to test with the latest prerelease?

**Comment by billynoah** [comment] 2024-02-23 02:01
@davidducos - thanks for following up. I'd be happy to try but not sure the best way to install.  I followed the instructions on the project home page - would I need to build from src? Can you direct me to a brief tutorial for doing this in Ubuntu 20?

**Comment by davidducos** [comment] 2024-02-26 13:55
Hi @billynoah, you can find the package in https://github.com/mydumper/mydumper/releases

**Comment by billynoah** [comment] 2024-02-26 14:24
Thanks - I didn't realize there were pre-releases in the releases page. I've got it installed.  I'll let you know how it goes.

**Comment by billynoah** [comment] 2024-02-26 16:54
@davidducos - Sorry if this has been addressed elsewhere but with the new version mydumper cannot connect.  Presumably some behaviour has changed in regards to the default config file it reads.  I have my client connection set up in ~/.my.cnf and this was working prior to switching to the pre-release.  Is this a bug or is there some new requirement to invoke mydumper so that it reads my user level config?

**Comment by davidducos** [comment] 2024-02-26 16:56
you can use `--defaults-extra-file="~/.my.cnf"` or with the absolute path.

**Comment by billynoah** [comment] 2024-02-26 16:58
Thanks, that works.  But is there any way to make this the standard behaviour without adding a command line option? Can I include that path somehow in the main config?

Also, please note the help output currently reads:
```
# You can modify them but we recommend you to use --default-extra-file
```

This is wrong as it should be:
```
# You can modify them but we recommend you to use --defaults-extra-file
```

**Comment by davidducos** [comment] 2024-02-27 11:49
Hi @billynoah, I'm checking what is going on...

**Comment by davidducos** [comment] 2024-02-27 13:26
Hi @billynoah,
I was not able to reproduce your issue. I compiled v0.15.1-3:
```
root@ubuntu-jammy:~/issue_0.15.1.3/mydumper# ./mydumper --version
mydumper v0.15.1-3, built against MySQL 5.7.44-48 with SSL support
```
And then I created this file:
```
root@ubuntu-jammy:~/issue_0.15.1.3/mydumper# cat /root/.my.cnf
[mydumper]
user =lala
```
I also tested with [client]. And in both cases it didn't fail which means that the file was not being loaded by default. 
It is failing if I set the file manually:
```
root@ubuntu-jammy:~/issue_0.15.1.3/mydumper# ./mydumper -B sbtest -o data -v 3 --defaults-extra-file=/root/.my.cnf
** Message: 13:25:20.642: MyDumper backup version: 0.15.1-3
** Message: 13:25:20.642: Parsing extra key file
** Message: 13:25:20.642: Config file loaded
** Message: 13:25:20.642: Merging config files user:

** (mydumper:44377): CRITICAL **: 13:25:20.670: Error connection to database: Access denied for user 'lala'@'localhost' (using password: NO)
root@ubuntu-jammy:~/issue_0.15.1.3/mydumper# ./mydumper -B sbtest -o data -v 3 --defaults-file=/root/.my.cnf
** Message: 13:25:24.754: MyDumper backup version: 0.15.1-3
** Message: 13:25:24.755: Config file loaded

** (mydumper:44378): CRITICAL **: 13:25:24.781: Error connection to database: Access denied for user 'lala'@'localhost' (using password: NO)
```
Can you share a testing case?

**Comment by billynoah** [comment] 2024-02-27 13:35
@davidducos - I apologize but I can't reproduce it now.  I reverted versions and the behaviour persists. My best guess is that I had added credentials to `/etc/mydumper.cnf`, forgotten about it, and then it got overwritten when I switched versions.

**Comment by davidducos** [comment] 2024-02-27 13:37
Ok, closing the issue now.

**Closed by davidducos** 2024-02-27 13:37 UTC
Labels: bug

**Comment by billynoah** [comment] 2024-02-27 13:42
@davidducos - We were sidetracking.  The defaults file issue should have been a separate ticket, or nothing at all.  This ticket is about the segmentation fault bug.  I'm not saying it hasn't been addressed, but as it's intermittent I really can't say.  Just wanted to make sure we aren't conflating one issue with the other.

And btw, thank you so much for your work on this project!  It's fantastic.
