### ISSUE TITLE
[BUG] MyDumper is using more memory than it should

### ISSUE THREAD

**Issue by Robertoh98** [mydumper/mydumper#857] opened 2022-10-11 20:46 UTC
**Describe the bug**
When we run the MyDumper on a table with big numbers on the bigint primary key it starts to use a lot of memory and take a long time to finish.

**To Reproduce**
Command executed:
$ mydumper --outputdir=./backup --tables-list=test.joinit --threads=8 --rows 1000000 --long-query-guard 3600 --build-empty-files --trx-consistency-only --database=test --statement-size=100000 --compress

What mydumper and myloader version has been used?
0.12.7-3

**Expected behavior**
The expected behavior would be the finish of the backup without using that amount of memory.

**Log**
Attaching the log file

**Backup**
```
$ ls -lah
total 20K
drwxr-x---. 2 root root 4.0K Oct 11 20:18 .
drwxr-x---. 3 root root 4.0K Oct 11 20:31 ..
-rw-r--r--. 1 root root  189 Oct 11 20:31 metadata.partial
-rw-r--r--. 1 root root  267 Oct 11 20:31 test.joinit-schema.sql.gz
-rw-r--r--. 1 root root  151 Oct 11 20:31 test-schema-create.sql.gz
```

**How to repeat**
To reproduce I created the following table:
```
CREATE TABLE `joinit` (
  `i` bigint unsigned NOT NULL AUTO_INCREMENT,
  `s` varchar(64) DEFAULT NULL,
  `t` time NOT NULL,
  `g` int NOT NULL,
  PRIMARY KEY (`i`)
) ENGINE=InnoDB AUTO_INCREMENT=1762913867643027359 DEFAULT CHARSET=latin1;
```
Then started to add lines: 
`INSERT INTO joinit VALUES (NULL, uuid(), time(now()),  (FLOOR( 1 + RAND( ) *60 )));`
Repeated this following insert until have a million rows:
`INSERT INTO joinit SELECT NULL, uuid(), time(now()),  (FLOOR( 1 + RAND( ) *60 )) FROM joinit;`

Then started the backup:
`$ mydumper --outputdir=./backup --tables-list=test.joinit --threads=8 --rows 1000000 --long-query-guard 3600 --build-empty-files --trx-consistency-only --database=test --statement-size=100000 --compress`

Looking at the top command we could notice the high use of memory:
```
[MyDumper.log](https://github.com/mydumper/mydumper/files/9759651/MyDumper.log)

top - 20:21:09 up  6:25,  2 users,  load average: 6.71, 6.91, 7.41
Tasks:  18 total,   2 running,  16 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.6 us,  0.6 sy,  0.0 ni, 97.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 39487513+total, 26513472+free, 12854912+used,  1191276 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 26632600+avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                       
   1346 root      20   0  122.1g 121.2g   8460 R 100.3 32.2   3:01.67 mydumper                                                                                                                                                                      
    826 mysql     20   0 4654884   1.4g 294032 S   0.3  0.4   2:53.80 mysqld   
```

**Environment (please complete the following information):**
```
$ cat /etc/*release*
CentOS Linux release 7.9.2009 (Core)
Derived from Red Hat Enterprise Linux 7.9 (Source)
$ mydumper --version
mydumper 0.12.7-3, built against MySQL 5.7.39-42
```

**Comment by davidducos** [comment] 2022-10-12 19:04
Hi @Robertoh98, I was not able to reproduce your issue.

**Comment by davidducos** [comment] 2022-10-13 12:30
Hi @Robertoh98,
I also tested higher version of CentOS:
```
[root@localhost mydumper]# git status
# HEAD detached at v0.12.7-3
...
[root@localhost mydumper]# ./mydumper --version
mydumper testing, built against MySQL 8.0.29-21
[root@localhost mydumper]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
```
And the rpm package on the same box:
```
[root@localhost mydumper]# mydumper --version
mydumper 0.12.7-3, built against MySQL 5.7.39-42
```
I did't see what you are describing.

**Comment by Robertoh98** [comment] 2022-10-13 23:04
Hi @davidducos, did you use the same versions? I was able to reproduce it again with the same versions: 
```
$ cat /etc/*release*
CentOS Linux release 7.9.2009 (Core)
Derived from Red Hat Enterprise Linux 7.9 (Source)
$ mydumper --version
mydumper 0.12.7-3, built against MySQL 5.7.39-42
$ mysql --version
mysql  Ver 8.0.29-21 for Linux on x86_64 (Percona Server (GPL), Release 21, Revision c59f87d2854)
```

The top:
````
top - 22:54:41 up 19 min,  2 users,  load average: 8.81, 4.41, 3.79
Tasks:  17 total,   2 running,  15 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.2 us,  0.0 sy,  0.0 ni, 95.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 19801796+total, 13196163+free, 65472568 used,   583760 buff/cache
KiB Swap:  4194300 total,  4194048 free,      252 used. 13254539+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                         
 4141 root      20   0   62.3g  61.5g   3612 R  99.7 32.5   2:07.64 mydumper                                                                                                                                                                        
 3990 mysql     20   0 3174972 853936   8640 S   0.7  0.4   3:11.02 mysqld                                                                                                                                                                          
 4092 root      20   0  148612   2812   1532 S   0.3  0.0   0:00.09 sshd   
````

I'm attaching the .sql from the table with the structure and data used.
[joinit.sql.zip](https://github.com/mydumper/mydumper/files/9781157/joinit.sql.zip)

**Comment by davidducos** [comment] 2022-10-14 15:25
Hi @Robertoh98, 
I was able to reproduce the issue, thanks for that file, was really useful. 
This will be fixed when we implement https://github.com/mydumper/mydumper/issues/529.

**Comment by davidducos** [comment] 2022-10-14 15:45
duplicate https://github.com/mydumper/mydumper/issues/848

**Comment by davidducos** [comment] 2022-10-25 21:15
hi @Robertoh98 
I need  you to test https://github.com/mydumper/mydumper/releases/tag/v0.13.0-1 to close this issue.

**Closed** 2022-11-02 20:12 UTC
Labels: bug
